# Generated by Django 4.2.5 on 2023-09-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=10)),
                ('education_level', models.CharField(max_length=10)),
                ('employment_status', models.CharField(max_length=10)),
                ('credit_utilization_ratio', models.FloatField()),
                ('payment_history', models.CharField(max_length=10)),
                ('number_of_credit_accounts', models.IntegerField()),
                ('loan_amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('loan_term', models.IntegerField()),
                ('type_of_loan', models.CharField(max_length=10)),
            ],
        ),
    ]
